"""
Tests for threading primitive (plugins/primitives/threading.py)
and the G76 block generated by cam/gcode_writer._threading_block().
"""

import sys
from pathlib import Path
import pytest

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from domain.profile import LatheProfile
from domain.recipe import OperationRecord, PartRecipe, StockSpec, ToolSequence
from domain.tool import SpindleMode, ToolDirection
from cam.gcode_writer import GCodeWriter, WriterConfig


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _threading_op(pitch=1.5, length_z=20.0, depth=0.0, first_pass=0.3,
                  spring_passes=1.0, infeed_angle=29.5,
                  direction=ToolDirection.EXTERNAL) -> OperationRecord:
    return OperationRecord(
        primitive_name="threading",
        params={
            "pitch": pitch,
            "length_z": length_z,
            "z_offset": 0.0,
            "depth": depth,
            "first_pass": first_pass,
            "spring_passes": spring_passes,
            "infeed_angle": infeed_angle,
        },
        direction=direction,
    )


def _build_profile_with_threading(tag=(0, 0), thread_d=30.0,
                                   z_start=0.0, z_end=-20.0) -> LatheProfile:
    """Manually build a profile with threading segments pre-tagged."""
    profile = LatheProfile(stock_d=40.0, stock_l=100.0)
    profile.active_tag = tag
    profile.add_line_to(d=thread_d, z=z_start)
    profile.add_line_to(d=thread_d, z=z_end)
    return profile


def _make_writer(op: OperationRecord, profile: LatheProfile) -> GCodeWriter:
    from domain.tool_library import ToolLibrary
    stock = StockSpec(diameter=40.0, length=100.0)
    seq = ToolSequence(
        tool_id=1,
        spindle_mode=SpindleMode.CSS,
        spindle_value=200.0,
        max_rpm=2000,
        coolant_on=False,
        operations=[op],
    )
    recipe = PartRecipe(part_name="test", stock=stock, tool_sequences=[seq])
    return GCodeWriter(recipe, profile, ToolLibrary.empty())


# ---------------------------------------------------------------------------
# ThreadingPrimitive unit tests
# ---------------------------------------------------------------------------

def _loader():
    from domain.plugin_loader import PrimitivePluginLoader
    loader = PrimitivePluginLoader()
    loader.load(ROOT / "plugins" / "primitives")
    return loader


def test_threading_primitive_loads():
    """Plugin loader must find and instantiate the threading primitive."""
    prim = _loader().get("threading")
    assert prim is not None
    assert prim.name == "threading"


def test_threading_params_schema():
    prim = _loader().get("threading")
    names = [p.name for p in prim.params_schema]
    assert "pitch" in names
    assert "length_z" in names
    assert "depth" in names
    assert "first_pass" in names
    assert "spring_passes" in names
    assert "infeed_angle" in names


def test_threading_build_does_not_change_diameter():
    """Threading must not change the nominal surface diameter."""
    from domain.profile import LatheProfile

    prim = _loader().get("threading")
    profile = LatheProfile(stock_d=40.0, stock_l=100.0)
    profile.add_cylinder(d=30.0, length=5.0)
    x_before = profile.cursor_x

    prim.build(profile, {
        "pitch": 1.5, "length_z": 20.0, "z_offset": 0.0,
        "depth": 0.0, "first_pass": 0.3, "spring_passes": 1.0,
        "infeed_angle": 29.5,
    })

    assert abs(profile.cursor_x - x_before) < 1e-6, (
        "Threading must not change the surface diameter"
    )


def test_threading_build_advances_cursor_z():
    from domain.profile import LatheProfile

    prim = _loader().get("threading")
    profile = LatheProfile(stock_d=40.0, stock_l=100.0)
    profile.add_cylinder(d=30.0, length=5.0)
    z_before = profile.cursor_z

    prim.build(profile, {
        "pitch": 1.5, "length_z": 20.0, "z_offset": 0.0,
        "depth": 0.0, "first_pass": 0.3, "spring_passes": 1.0,
        "infeed_angle": 29.5,
    })

    assert profile.cursor_z < z_before, "cursor_z must advance in -Z direction"
    assert abs(profile.cursor_z - (z_before - 20.0)) < 1e-6


def test_threading_validate_rejects_large_first_pass():
    from domain.primitive_base import ProfileContext

    prim = _loader().get("threading")
    ctx = ProfileContext(cursor_x=30.0, cursor_z=0.0, stock_d=40.0, stock_l=100.0, segment_count=1)
    err = prim.validate({
        "pitch": 1.5, "length_z": 20.0, "z_offset": 0.0,
        "depth": 0.9, "first_pass": 1.0,  # first_pass >= depth
        "spring_passes": 1.0, "infeed_angle": 29.5,
    }, ctx)
    assert err is not None


def test_threading_validate_rejects_overlong_thread():
    from domain.primitive_base import ProfileContext

    prim = _loader().get("threading")
    ctx = ProfileContext(cursor_x=30.0, cursor_z=-80.0, stock_d=40.0, stock_l=100.0, segment_count=1)
    err = prim.validate({
        "pitch": 1.5, "length_z": 50.0, "z_offset": 0.0,  # -80 - 50 = -130 > -100
        "depth": 0.9, "first_pass": 0.3,
        "spring_passes": 1.0, "infeed_angle": 29.5,
    }, ctx)
    assert err is not None


# ---------------------------------------------------------------------------
# GCodeWriter — G76 block generation
# ---------------------------------------------------------------------------

def test_gcode_writer_threading_produces_g76():
    op = _threading_op(pitch=1.5, length_z=20.0)
    profile = _build_profile_with_threading(tag=(0, 0), z_start=0.0, z_end=-20.0)
    writer = _make_writer(op, profile)
    lines = writer.generate_lines()
    g76_lines = [l for l in lines if "G76" in l]
    assert len(g76_lines) == 1, f"Expected exactly one G76 line, got: {g76_lines}"


def test_gcode_writer_threading_pitch_in_g76():
    op = _threading_op(pitch=2.0)
    profile = _build_profile_with_threading(tag=(0, 0))
    writer = _make_writer(op, profile)
    lines = writer.generate_lines()
    g76 = next(l for l in lines if "G76" in l)
    assert "P2.0000" in g76, f"Pitch P2.0000 not found in: {g76}"


def test_gcode_writer_threading_z_end_in_g76():
    op = _threading_op(pitch=1.5, length_z=30.0)
    profile = _build_profile_with_threading(tag=(0, 0), z_start=0.0, z_end=-30.0)
    writer = _make_writer(op, profile)
    lines = writer.generate_lines()
    g76 = next(l for l in lines if "G76" in l)
    assert "Z-30.000" in g76, f"Z-30.000 not found in: {g76}"


def test_gcode_writer_threading_approach_rapid():
    """Must have G0 rapid approach before G76."""
    op = _threading_op()
    profile = _build_profile_with_threading(tag=(0, 0))
    writer = _make_writer(op, profile)
    lines = writer.generate_lines()
    thread_idx = next(i for i, l in enumerate(lines) if "threading" in l)
    g0_before = [l for l in lines[thread_idx:thread_idx + 3] if l.startswith("G0")]
    assert g0_before, "Expected G0 rapid before G76"


def test_gcode_writer_threading_retract_after():
    """Must have G0 retract to safe X after G76."""
    op = _threading_op()
    profile = _build_profile_with_threading(tag=(0, 0))
    writer = _make_writer(op, profile)
    lines = writer.generate_lines()
    g76_idx = next(i for i, l in enumerate(lines) if "G76" in l)
    assert lines[g76_idx + 1].startswith("G0"), "Expected G0 retract after G76"


def test_gcode_writer_no_g76_without_threading_op():
    """Recipe without threading must not produce any G76 line."""
    from domain.tool_library import ToolLibrary
    profile = LatheProfile(stock_d=40.0, stock_l=100.0)
    profile.add_cylinder(d=30.0, length=50.0)
    stock = StockSpec(diameter=40.0, length=100.0)
    seq = ToolSequence(
        tool_id=1, coolant_on=False,
        operations=[OperationRecord("cylinder", {"d": 30.0, "length": 50.0})],
    )
    recipe = PartRecipe(stock=stock, tool_sequences=[seq])
    writer = GCodeWriter(recipe, profile, ToolLibrary.empty())
    lines = writer.generate_lines()
    assert not any("G76" in l for l in lines)


def test_gcode_writer_threading_auto_depth():
    """depth=0 should auto-calculate depth as 0.6495 * pitch."""
    op = _threading_op(pitch=1.5, depth=0.0, first_pass=0.3)
    profile = _build_profile_with_threading(tag=(0, 0))
    writer = _make_writer(op, profile)
    lines = writer.generate_lines()
    g76 = next(l for l in lines if "G76" in l)
    expected_depth = 0.6495 * 1.5  # = 0.97425
    assert f"K{expected_depth:.3f}" in g76, (
        f"Expected K{expected_depth:.3f} in: {g76}"
    )
