"""
Tests for threading primitive (plugins/primitives/threading.py)
and the G76 block generated by cam/gcode_writer._threading_block().
"""

import sys
from pathlib import Path
import pytest

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from domain.profile import LatheProfile
from domain.recipe import OperationRecord, PartRecipe, StockSpec, ToolSequence
from domain.tool import SpindleMode, ToolDirection
from cam.gcode_writer import GCodeWriter, WriterConfig


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _threading_op(pitch=1.5, length_z=20.0, depth=0.0, first_pass=0.3,
                  spring_passes=1.0, infeed_mode=1, std_idx=0,
                  direction=ToolDirection.EXTERNAL) -> OperationRecord:
    return OperationRecord(
        primitive_name="threading",
        params={
            "std_idx": float(std_idx),   # 0 = manual, 1+ = standard table
            "pitch": pitch,
            "length_z": length_z,
            "z_offset": 0.0,
            "depth": depth,
            "first_pass": first_pass,
            "spring_passes": spring_passes,
            "infeed_mode": float(infeed_mode),
        },
        direction=direction,
    )


def _build_profile_with_threading(tag=(0, 0), thread_d=30.0,
                                   z_start=0.0, z_end=-20.0) -> LatheProfile:
    """Manually build a profile with threading segments pre-tagged."""
    profile = LatheProfile(stock_d=40.0, stock_l=100.0)
    profile.active_tag = tag
    profile.add_line_to(d=thread_d, z=z_start)
    profile.add_line_to(d=thread_d, z=z_end)
    return profile


def _make_writer(op: OperationRecord, profile: LatheProfile) -> GCodeWriter:
    from domain.tool_library import ToolLibrary
    stock = StockSpec(diameter=40.0, length=100.0)
    seq = ToolSequence(
        tool_id=1,
        spindle_mode=SpindleMode.CSS,
        spindle_value=200.0,
        max_rpm=2000,
        coolant_on=False,
        operations=[op],
    )
    recipe = PartRecipe(part_name="test", stock=stock, tool_sequences=[seq])
    return GCodeWriter(recipe, profile, ToolLibrary.empty())


# ---------------------------------------------------------------------------
# ThreadingPrimitive unit tests
# ---------------------------------------------------------------------------

def _loader():
    from domain.plugin_loader import PrimitivePluginLoader
    loader = PrimitivePluginLoader()
    loader.load(ROOT / "plugins" / "primitives")
    return loader


def test_threading_primitive_loads():
    """Plugin loader must find and instantiate the threading primitive."""
    prim = _loader().get("threading")
    assert prim is not None
    assert prim.name == "threading"


def test_threading_params_schema():
    prim = _loader().get("threading")
    names = [p.name for p in prim.params_schema]
    assert "std_idx"       in names
    assert "pitch"         in names
    assert "length_z"      in names
    assert "depth"         in names
    assert "first_pass"    in names
    assert "spring_passes" in names
    assert "infeed_mode"   in names


def test_threading_build_does_not_change_diameter():
    """Threading must not change the nominal surface diameter."""
    from domain.profile import LatheProfile

    prim = _loader().get("threading")
    profile = LatheProfile(stock_d=40.0, stock_l=100.0)
    profile.add_cylinder(d=30.0, length=5.0)
    x_before = profile.cursor_x

    prim.build(profile, {
        "std_idx": 0.0, "pitch": 1.5, "length_z": 20.0, "z_offset": 0.0,
        "depth": 0.0, "first_pass": 0.3, "spring_passes": 1.0,
        "infeed_mode": 1.0,
    })

    assert abs(profile.cursor_x - x_before) < 1e-6, (
        "Threading must not change the surface diameter"
    )


def test_threading_build_advances_cursor_z():
    from domain.profile import LatheProfile

    prim = _loader().get("threading")
    profile = LatheProfile(stock_d=40.0, stock_l=100.0)
    profile.add_cylinder(d=30.0, length=5.0)
    z_before = profile.cursor_z

    prim.build(profile, {
        "std_idx": 0.0, "pitch": 1.5, "length_z": 20.0, "z_offset": 0.0,
        "depth": 0.0, "first_pass": 0.3, "spring_passes": 1.0,
        "infeed_mode": 1.0,
    })

    assert profile.cursor_z < z_before, "cursor_z must advance in -Z direction"
    assert abs(profile.cursor_z - (z_before - 20.0)) < 1e-6


def test_threading_validate_rejects_large_first_pass():
    from domain.primitive_base import ProfileContext

    prim = _loader().get("threading")
    ctx = ProfileContext(cursor_x=30.0, cursor_z=0.0, stock_d=40.0, stock_l=100.0, segment_count=1)
    err = prim.validate({
        "std_idx": 0.0, "pitch": 1.5, "length_z": 20.0, "z_offset": 0.0,
        "depth": 0.9, "first_pass": 1.0,  # first_pass >= depth
        "spring_passes": 1.0, "infeed_mode": 1.0,
    }, ctx)
    assert err is not None


def test_threading_validate_rejects_overlong_thread():
    from domain.primitive_base import ProfileContext

    prim = _loader().get("threading")
    ctx = ProfileContext(cursor_x=30.0, cursor_z=-80.0, stock_d=40.0, stock_l=100.0, segment_count=1)
    err = prim.validate({
        "std_idx": 0.0, "pitch": 1.5, "length_z": 50.0, "z_offset": 0.0,  # -80 - 50 = -130 > -100
        "depth": 0.9, "first_pass": 0.3,
        "spring_passes": 1.0, "infeed_mode": 1.0,
    }, ctx)
    assert err is not None


# ---------------------------------------------------------------------------
# GCodeWriter — G76 block generation
# ---------------------------------------------------------------------------

def test_gcode_writer_threading_produces_g76():
    op = _threading_op(pitch=1.5, length_z=20.0)
    profile = _build_profile_with_threading(tag=(0, 0), z_start=0.0, z_end=-20.0)
    writer = _make_writer(op, profile)
    lines = writer.generate_lines()
    g76_lines = [l for l in lines if "G76" in l]
    assert len(g76_lines) == 1, f"Expected exactly one G76 line, got: {g76_lines}"


def test_gcode_writer_threading_pitch_in_g76():
    op = _threading_op(pitch=2.0)
    profile = _build_profile_with_threading(tag=(0, 0))
    writer = _make_writer(op, profile)
    lines = writer.generate_lines()
    g76 = next(l for l in lines if "G76" in l)
    assert "P2.0000" in g76, f"Pitch P2.0000 not found in: {g76}"


def test_gcode_writer_threading_z_end_in_g76():
    op = _threading_op(pitch=1.5, length_z=30.0)
    profile = _build_profile_with_threading(tag=(0, 0), z_start=0.0, z_end=-30.0)
    writer = _make_writer(op, profile)
    lines = writer.generate_lines()
    g76 = next(l for l in lines if "G76" in l)
    assert "Z-30.000" in g76, f"Z-30.000 not found in: {g76}"


def test_gcode_writer_threading_approach_rapid():
    """Must have G0 rapid approach before G76."""
    op = _threading_op()
    profile = _build_profile_with_threading(tag=(0, 0))
    writer = _make_writer(op, profile)
    lines = writer.generate_lines()
    thread_idx = next(i for i, l in enumerate(lines) if "threading" in l)
    g0_before = [l for l in lines[thread_idx:thread_idx + 3] if l.startswith("G0")]
    assert g0_before, "Expected G0 rapid before G76"


def test_gcode_writer_threading_retract_after():
    """Must have G0 retract to safe X after G76."""
    op = _threading_op()
    profile = _build_profile_with_threading(tag=(0, 0))
    writer = _make_writer(op, profile)
    lines = writer.generate_lines()
    g76_idx = next(i for i, l in enumerate(lines) if "G76" in l)
    assert lines[g76_idx + 1].startswith("G0"), "Expected G0 retract after G76"


def test_gcode_writer_no_g76_without_threading_op():
    """Recipe without threading must not produce any G76 line."""
    from domain.tool_library import ToolLibrary
    profile = LatheProfile(stock_d=40.0, stock_l=100.0)
    profile.add_cylinder(d=30.0, length=50.0)
    stock = StockSpec(diameter=40.0, length=100.0)
    seq = ToolSequence(
        tool_id=1, coolant_on=False,
        operations=[OperationRecord("cylinder", {"d": 30.0, "length": 50.0})],
    )
    recipe = PartRecipe(stock=stock, tool_sequences=[seq])
    writer = GCodeWriter(recipe, profile, ToolLibrary.empty())
    lines = writer.generate_lines()
    assert not any("G76" in l for l in lines)


def test_gcode_writer_threading_auto_depth():
    """depth=0 should auto-calculate depth as 0.6495 * pitch."""
    op = _threading_op(pitch=1.5, depth=0.0, first_pass=0.3)
    profile = _build_profile_with_threading(tag=(0, 0))
    writer = _make_writer(op, profile)
    lines = writer.generate_lines()
    g76 = next(l for l in lines if "G76" in l)
    expected_depth = 0.6495 * 1.5  # = 0.97425
    assert f"K{expected_depth:.3f}" in g76, (
        f"Expected K{expected_depth:.3f} in: {g76}"
    )


def test_standard_thread_std_idx_uses_table():
    """std_idx > 0 should pull pitch and depth from the thread table."""
    from domain.thread_data import THREADS, get_effective_thread
    # M6 coarse is index 5 in THREADS (0-based), so std_idx=6 (offset by 1 for Manual)
    spec = THREADS[5]  # M6 p=1.00
    assert abs(spec.pitch_mm - 1.0) < 1e-6
    params = {"std_idx": 6.0, "pitch": 99.0, "depth": 0.0, "infeed_mode": 1.0,
              "length_z": 20.0, "z_offset": 0.0, "first_pass": 0.3, "spring_passes": 1.0}
    pitch, depth, taper = get_effective_thread(params)
    assert abs(pitch - 1.0) < 1e-6, "Should use table pitch, not manual 99.0"
    assert abs(depth - spec.depth_mm) < 1e-6
    assert taper == 0.0  # M6 is cylindrical


def test_npt_thread_has_nonzero_taper():
    """NPT threads must have taper_rate > 0."""
    from domain.thread_data import THREADS, get_effective_thread
    npt_specs = [t for t in THREADS if t.family == "npt"]
    assert npt_specs, "No NPT threads in table"
    for s in npt_specs:
        assert s.taper_rate > 0.0, f"{s.label} has zero taper_rate"


def test_gcode_writer_npt_thread_has_nonzero_i():
    """NPT threading G76 must have a non-zero I taper parameter."""
    from domain.thread_data import THREADS
    # Find 1/2" NPT: tpi=14, pitch ≈ 1.8143
    npt_idx = next(i for i, t in enumerate(THREADS) if t.family == "npt")
    op = _threading_op(std_idx=npt_idx + 1, first_pass=0.2)  # +1 for Manual offset
    profile = _build_profile_with_threading(tag=(0, 0), z_start=0.0, z_end=-20.0)
    writer = _make_writer(op, profile)
    lines = writer.generate_lines()
    g76 = next(l for l in lines if "G76" in l)
    # Extract I value
    import re
    m = re.search(r"I(-?\d+\.\d+)", g76)
    assert m is not None, f"I parameter not found in: {g76}"
    i_val = float(m.group(1))
    assert abs(i_val) > 1e-6, f"NPT I should be non-zero, got {i_val}"


def test_infeed_mode_radial_gives_q0():
    """infeed_mode=0 (radial) should produce Q0.0 in G76."""
    op = _threading_op(infeed_mode=0)
    profile = _build_profile_with_threading(tag=(0, 0))
    writer = _make_writer(op, profile)
    lines = writer.generate_lines()
    g76 = next(l for l in lines if "G76" in l)
    assert "Q0.0" in g76, f"Expected Q0.0 for radial infeed in: {g76}"


def test_infeed_mode_leading_gives_q29():
    """infeed_mode=1 (leading flank) should produce Q29.5 in G76."""
    op = _threading_op(infeed_mode=1)
    profile = _build_profile_with_threading(tag=(0, 0))
    writer = _make_writer(op, profile)
    lines = writer.generate_lines()
    g76 = next(l for l in lines if "G76" in l)
    assert "Q29.5" in g76, f"Expected Q29.5 for leading flank in: {g76}"
