"""
GCodeWriter — assembles a complete LinuxCNC G-code program from a PartRecipe.

Inputs
------
  recipe        : PartRecipe (tool sequences + operations)
  profile       : LatheProfile already built from the recipe operations
  tool_library  : ToolLibrary to look up cutting data
  machine       : MachineConfig for safe positions, RPM cap, etc.

Output
------
  A single string (or list of lines) containing the complete G-code program.

Program structure
-----------------
  Header block   : G21 G18 G90 G40 ; metric, XZ plane, absolute, cancel comp
  For each ToolSequence:
    Rapid to z_tool_change (safe), then x_tool_change
    T{id} M6                    ; tool change
    Spindle setup (G96 or G97)
    M8 if coolant_on
    Roughing block (ExternalRougher passes) — only if has roughing ops
    Finishing block (FinishingPass contour)
    Parting block — if last op is parting
    M9 (coolant off)
    Retract to x_clearance
  Footer: G00 to home, M5 M30
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING

from cam.finishing import FinishingPass
from cam.operator_msg import MessageCatalogue
from cam.parting import parting_lines
from cam.roughing import ExternalRougher, RoughingPass
from domain.app_config import AppConfig
from domain.tool import SpindleMode, ToolDirection

if TYPE_CHECKING:
    from domain.machine import MachineConfig
    from domain.profile import LatheProfile
    from domain.recipe import OperationRecord, PartRecipe
    from domain.tool_library import ToolLibrary


_HEADER = [
    "(Generated by LatheCadCam)",
    "G21        (metric)",
    "G18        (XZ plane)",
    "G90        (absolute)",
    "G40        (cancel tool radius comp)",
    "G49        (cancel tool length comp)",
]

_FOOTER_BEFORE_HOME = ["M9         (coolant off)", "M5         (spindle off)"]
_PROGRAM_END        = "M30"


def _fmt(v: float) -> str:
    return f"{v:.3f}"


# ---------------------------------------------------------------------------

@dataclass
class WriterConfig:
    """Tunable parameters for the G-code writer."""
    arc_resolution:     int   = 32
    step_down:          float = 1.0
    finish_allowance:   float = 0.3
    approach_clearance: float = 2.0
    default_feed_rough: float = 150.0
    default_feed_finish: float = 100.0


class GCodeWriter:

    def __init__(
        self,
        recipe:       "PartRecipe",
        profile:      "LatheProfile",
        tool_library: "ToolLibrary",
        machine:      "MachineConfig | None" = None,
        config:       WriterConfig | None    = None,
        app_config:   AppConfig | None       = None,
    ) -> None:
        self._recipe   = recipe
        self._profile  = profile
        self._tools    = tool_library
        self._machine  = machine
        self._cfg      = config or WriterConfig()
        self._catalogue = MessageCatalogue(app_config or AppConfig())

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(self) -> str:
        self._catalogue.reset()
        lines = self._build_lines()
        self._catalogue.flush()
        return "\n".join(lines)

    def generate_lines(self) -> list[str]:
        self._catalogue.reset()
        lines = self._build_lines()
        self._catalogue.flush()
        return lines

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _build_lines(self) -> list[str]:
        lines: list[str] = []
        lines.extend(_HEADER)
        lines.append("")

        stock   = self._recipe.stock
        stock_r = stock.diameter / 2.0

        safe_x_r  = stock_r + 5.0
        safe_z_tc = 50.0
        x_tc_r    = stock_r + 10.0
        x_home_r  = stock_r + 10.0
        z_home    = 50.0

        if self._machine:
            sp        = self._machine.safe
            safe_x_r  = sp.x_clearance
            safe_z_tc = sp.z_tool_change
            x_tc_r    = sp.x_tool_change
            x_home_r  = sp.x_home
            z_home    = sp.z_home

        for seq in self._recipe.tool_sequences:
            lines.extend(
                self._sequence_block(seq, stock_r, safe_x_r, safe_z_tc,
                                     x_tc_r, x_home_r, z_home)
            )
            lines.append("")

        lines.extend(_FOOTER_BEFORE_HOME)
        lines.append(
            f"G0 X{_fmt(x_home_r * 2.0)} Z{_fmt(z_home)}"
            "  (return to home)"
        )
        lines.append(_PROGRAM_END)
        return lines

    def _sequence_block(
        self, seq, stock_r, safe_x_r, safe_z_tc, x_tc_r, x_home_r, z_home
    ) -> list[str]:
        lines: list[str] = []
        tool   = self._tools.get_by_id(seq.tool_id)
        nose_r = tool.insert.nose_radius if tool else 0.4

        lines.append(f"(--- Tool {seq.tool_id} ---)")
        lines.append(f"G0 X{_fmt(x_tc_r * 2.0)} Z{_fmt(safe_z_tc)}")
        lines.append(f"T{seq.tool_id:02d} M6")
        lines.extend(self._spindle_lines(seq, stock_r))

        if seq.coolant_on:
            lines.append("M8")

        cap = self._machine.cap_rpm if self._machine else None
        for op in seq.operations:
            if not op.enabled:
                continue
            if op.primitive_name == "operator_message":
                lines.extend(self._catalogue.operator_message_lines(op))
            elif op.primitive_name == "manual_spindle":
                lines.extend(
                    self._catalogue.manual_spindle_lines(op, cap, seq.max_rpm)
                )

        feed_r, feed_f = self._feed_rates(seq, stock_r, tool)

        _SKIP = {"parting", "rapid_to", "operator_message", "manual_spindle"}
        has_machining = any(
            op.enabled for op in seq.operations if op.primitive_name not in _SKIP
        )

        if has_machining:
            lines.extend(self._roughing_block(stock_r, nose_r, feed_r, safe_x_r))

        if has_machining:
            direction = seq.operations[0].direction if seq.operations else ToolDirection.EXTERNAL
            internal  = (direction == ToolDirection.INTERNAL)
            fin = FinishingPass(
                profile=self._profile,
                feed_rate=feed_f,
                tool_id=seq.tool_id,
                internal=internal,
                approach_z=self._cfg.approach_clearance,
                approach_r=safe_x_r,
                retract_r=safe_x_r,
                nose_radius=nose_r,
            )
            lines.append("(--- finishing ---)")
            lines.extend(fin.lines())

        for op in seq.operations:
            if op.enabled and op.primitive_name == "parting":
                lines.append("(--- parting ---)")
                lines.extend(
                    parting_lines(op.params, self._profile.cursor_x / 2.0,
                                  feed_r, safe_x_r)
                )
                break

        if seq.coolant_on:
            lines.append("M9")
        lines.append(f"G0 X{_fmt(safe_x_r * 2.0)}")
        return lines

    def _spindle_lines(self, seq, stock_r: float) -> list[str]:
        max_rpm = seq.max_rpm
        if self._machine:
            max_rpm = self._machine.cap_rpm(max_rpm)
        if seq.spindle_mode == SpindleMode.CSS:
            return [f"G96 S{seq.spindle_value:.0f} D{max_rpm} M3  (CSS m/min)"]
        rpm = min(seq.spindle_value, max_rpm)
        return [f"G97 S{rpm:.0f} M3  (constant RPM)"]

    def _feed_rates(self, seq, stock_r: float, tool) -> tuple[float, float]:
        feed_r = self._cfg.default_feed_rough
        feed_f = self._cfg.default_feed_finish
        if tool:
            cd = tool.best_data(self._recipe.stock.material_key)
            if cd:
                d_est   = stock_r * 2.0 * 0.75
                rpm_est = cd.rpm_for_diameter(d_est) if d_est > 0 else 1000
                feed_r  = round(cd.fn_rec * rpm_est, 0)
                feed_f  = round(cd.fn_rec * rpm_est * 0.8, 0)
        return feed_r, feed_f

    def _roughing_block(
        self, stock_r: float, nose_r: float, feed_r: float, safe_x_r: float
    ) -> list[str]:
        rougher = ExternalRougher(
            profile=self._profile,
            stock_r=stock_r,
            stock_l=self._recipe.stock.length,
            step_down=self._cfg.step_down,
            feed_rate=feed_r,
            finish_allowance=self._cfg.finish_allowance,
            nose_radius=nose_r,
        )
        passes = rougher.generate()
        if not passes:
            return []
        lines = ["(--- roughing ---)"]
        for rp in passes:
            lines.append(f"G0 X{_fmt(safe_x_r * 2.0)}")
            if rp.moves:
                z_approach = rp.moves[0][1] + self._cfg.approach_clearance
                lines.append(f"G0 Z{_fmt(z_approach)}")
                lines.append(f"G0 X{_fmt(rp.radius * 2.0)}")
                for r, z in rp.moves:
                    lines.append(f"G1 X{_fmt(r * 2.0)} Z{_fmt(z)} F{rp.feed_rate:.0f}")
        return lines
